# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointHod.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import sys
sys.path.append("D:\\Projects_Sem-3\\Python-I_Individual\\Demo")
from hod import Hod
from project import Project

class Ui_Dialog(object):
    hod = Hod()
    project = Project()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(803, 575)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(-10, 0, 811, 581))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0.419, y1:0.767227, x2:1, y2:0.534, stop:0 rgba(147, 165, 207, 255), stop:1 rgba(228, 239, 233, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(229, 20, 421, 111))
        self.label.setStyleSheet("font: 24pt \"Sans Serif Collection\";")
        self.label.setObjectName("label")
        self.hodName = QtWidgets.QLineEdit(self.bgwidget)
        self.hodName.setGeometry(QtCore.QRect(210, 160, 451, 61))
        self.hodName.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.hodName.setText("")
        self.hodName.setObjectName("hodName")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 131, 51))
        self.label_2.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 250, 131, 51))
        self.label_3.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.hodEmail = QtWidgets.QLineEdit(self.bgwidget)
        self.hodEmail.setGeometry(QtCore.QRect(210, 250, 451, 61))
        self.hodEmail.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.hodEmail.setText("")
        self.hodEmail.setObjectName("hodEmail")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(74, 340, 131, 51))
        self.label_4.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.hodNumber = QtWidgets.QLineEdit(self.bgwidget)
        self.hodNumber.setGeometry(QtCore.QRect(210, 340, 451, 61))
        self.hodNumber.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.hodNumber.setText("")
        self.hodNumber.setObjectName("hodNumber")
        self.hodBtn = QtWidgets.QPushButton(self.bgwidget)
        self.hodBtn.setGeometry(QtCore.QRect(240, 480, 391, 61))
        self.hodBtn.setStyleSheet("border-radius:8px;\n"
"border:3px solid rgb(139, 139, 139);\n"
"background-color:rgba(0,0,0,0);\n"
"font: 22pt \"Sans Serif Collection\";")
        self.hodBtn.setObjectName("hodBtn")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(210, 420, 441, 41))
        self.error.setStyleSheet("font: 14pt \"Sans Serif Collection\";\n"
"color:red;\n"
"background-color: rgba(0,0,0,0);")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.hodBtn.clicked.connect(self.store_data)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter the details of Hod"))
        self.label_2.setText(_translate("Dialog", "Name:"))
        self.label_3.setText(_translate("Dialog", "Email:"))
        self.label_4.setText(_translate("Dialog", "Number:"))
        self.hodBtn.setText(_translate("Dialog", "Appoint Hod"))
        
    def store_data(self):
        self.hod.name = hodName = self.hodName.text()
        self.hod.mail = hodEmail = self.hodEmail.text()
        self.hod.phone = hodNumber = self.hodNumber.text()

        if(len(hodName) == 0 or len(hodEmail) == 0 or len(hodNumber) == 0):
            self.error.setText("Please fill all fields!!")
        elif(not(self.hod.is_valid_emailid(hodEmail))):
            self.error.setText("Please Enter valid email id!!")
        elif(not(self.hod.is_valid_number(hodNumber))):
            self.error.setText("Please Enter valid number!!")
        else:
            self.hod.userId = hodUserid = self.hod.generate_userid()
            self.hod.password = hodPass = self.hod.generate_pass()
            mydb = self.project.connector()
            mycursor = mydb.cursor()
            query = "INSERT INTO hod (UserId,password,name,phone,mail) VALUES (%s, %s, %s, %s, %s)"
            value = (hodUserid,hodPass,hodName,hodNumber,hodEmail)

            mycursor.execute(query,value)
            mydb.commit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())