# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classForFaculty.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
sys.path.append("D:\\Projects_Sem-3\\Python-I_Individual\\Demo")
from project import Project

class Ui_Dialog(object):
    def setupUi(self, Dialog,i):
        self.i = i
        Dialog.setObjectName("Dialog")
        Dialog.resize(920, 480)
        Dialog.setStyleSheet("")
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 920, 481))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0.419, y1:0.767227, x2:1, y2:0.534, stop:0 rgba(147, 165, 207, 255), stop:1 rgba(228, 239, 233, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.class_2 = QtWidgets.QLabel(self.bgwidget)
        self.class_2.setGeometry(QtCore.QRect(230, 40, 691, 61))
        self.class_2.setStyleSheet("font: 24pt \"Sans Serif Collection\";")
        self.class_2.setText("")
        self.class_2.setObjectName("class_2")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 131, 51))
        self.label_2.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 150, 131, 51))
        self.label_3.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 131, 51))
        self.label_4.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(504, 260, 131, 51))
        self.label_5.setStyleSheet("font: 18pt \"Sans Serif Collection\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.submit = QtWidgets.QPushButton(self.bgwidget, clicked = lambda: self.go_hod)
        self.submit.setGeometry(QtCore.QRect(270, 380, 391, 61))
        self.submit.setStyleSheet("border-radius:8px;\n"
"border:3px solid rgb(139, 139, 139);\n"
"background-color:rgba(0,0,0,0);\n"
"font: 22pt \"Sans Serif Collection\";")
        self.submit.setObjectName("submit")
        self.pythonFaculty = QtWidgets.QComboBox(self.bgwidget)
        self.pythonFaculty.setGeometry(QtCore.QRect(140, 150, 301, 61))
        self.pythonFaculty.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.pythonFaculty.setObjectName("pythonFaculty")
        self.fsdFaculty = QtWidgets.QComboBox(self.bgwidget)
        self.fsdFaculty.setGeometry(QtCore.QRect(560, 150, 301, 61))
        self.fsdFaculty.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.fsdFaculty.setObjectName("fsdFaculty")
        self.deFaculty = QtWidgets.QComboBox(self.bgwidget)
        self.deFaculty.setGeometry(QtCore.QRect(140, 260, 301, 61))
        self.deFaculty.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.deFaculty.setObjectName("deFaculty")
        self.psFaculty = QtWidgets.QComboBox(self.bgwidget)
        self.psFaculty.setGeometry(QtCore.QRect(560, 260, 301, 61))
        self.psFaculty.setStyleSheet("border-radius:17px;\n"
"background-color:rgba(0,0,0,0);\n"
"border:3px solid rgb(139, 139, 139);\n"
"font: 18pt \"Sans Serif Collection\";")
        self.psFaculty.setObjectName("psFaculty")

        p = Project()
        python_faculties = p.get_python_faculties()
        fsd_faculties = p.get_fsd_faculties()
        de_faculties = p.get_de_faculties()
        ps_faculties = p.get_ps_faculties()

        self.pythonFaculty.addItems(python_faculties)
        self.fsdFaculty.addItems(fsd_faculties)
        self.deFaculty.addItems(de_faculties)
        self.psFaculty.addItems(ps_faculties)

        self.pythonFaculty.activated.connect(self.add_python_faculty)
        self.fsdFaculty.activated.connect(self.add_fsd_faculty)
        self.deFaculty.activated.connect(self.add_de_faculty)
        self.psFaculty.activated.connect(self.add_ps_faculty)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

#     def go_hod(self):

    def add_python_faculty(self):
        self.i.python_faculty = self.pythonFaculty.currentText()
    def add_fsd_faculty(self):
        self.i.python_faculty = self.fsdFaculty.currentText()
    def add_de_faculty(self):
        self.i.python_faculty = self.deFaculty.currentText()
    def add_ps_faculty(self):
        self.i.python_faculty = self.psFaculty.currentText()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Python:"))
        self.label_3.setText(_translate("Dialog", "FSD:"))
        self.label_4.setText(_translate("Dialog", "DE:"))
        self.label_5.setText(_translate("Dialog", "PS:"))
        self.submit.setText(_translate("Dialog", "Submit"))



